"""Regenerate one launcher stub per cataloged experiment (manager tool).

    scqo sync-launchers --dir <driver-repo>/scripts/experiments

Run after promoting/registering a new experiment so it appears as a directly
runnable script in the driver repos. Requires a driver venv (the catalog fills via
the driver's ``scqo.experiments`` entry point). Stubs are AUTO-GENERATED — never
edit them by hand. Each driver's ``scripts/experiments/_sync.py`` wrapper calls
this with its own folder.
"""

from __future__ import annotations

import argparse
from pathlib import Path

TEMPLATE = '''"""Run {name} directly (AUTO-GENERATED by _sync.py — regenerate, never edit).

{description}

    python scripts/experiments/{name}.py --qubits q0 q1 --tag mytag
    python scripts/experiments/{name}.py --help        # full parameter list
    (equivalent: scqo run {name} ... — works from any directory)
"""

import sys

from scqo.cli import run_experiment_cli

if __name__ == "__main__":
    sys.exit(run_experiment_cli("{name}", doc=__doc__))
'''


def main(argv: list[str] | None = None, prog: str | None = None) -> int:
    parser = argparse.ArgumentParser(prog=prog, description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dir", required=True, metavar="PATH",
                        help="the driver repo's scripts/experiments folder to write stubs into")
    args = parser.parse_args(argv)

    from scqo import catalog  # entry-point discovery registers the driver's experiments

    entries = catalog()
    if not entries:
        raise SystemExit("no experiments registered — run this from a driver venv "
                         "(the catalog fills via the driver's scqo.experiments entry point)")
    target = Path(args.dir)
    if not target.is_dir():
        raise SystemExit(f"not a directory: {target}")
    generated = []
    for entry in entries:
        path = target / f"{entry['name']}.py"
        path.write_text(TEMPLATE.format(name=entry["name"], description=entry["description"]),
                        encoding="utf-8")
        generated.append(entry["name"])
    print(f"generated {len(generated)} launcher(s) in {target}: {', '.join(sorted(generated))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
